from __future__ import annotations

"""
H1 report drafter — converts a Finding into a ready-to-submit
HackerOne report in clean Markdown.

The output is opinionated: it follows H1's preferred structure and
uses concrete, reviewer-friendly language so reports get triaged faster.
"""

from datetime import datetime, timezone

from recon_agent.core.state import Finding, Severity

_SEVERITY_LABEL = {
    Severity.CRITICAL: "Critical",
    Severity.HIGH: "High",
    Severity.MEDIUM: "Medium",
    Severity.LOW: "Low",
    Severity.INFO: "Informational",
}

_CVSS_BY_SEVERITY = {
    Severity.CRITICAL: "9.0–10.0",
    Severity.HIGH: "7.0–8.9",
    Severity.MEDIUM: "4.0–6.9",
    Severity.LOW: "0.1–3.9",
    Severity.INFO: "0.0",
}

_IMPACT_BY_TOOL = {
    "jssecrets": "An attacker who discovers this credential can authenticate as the "
                 "application to the affected third-party service, potentially leading "
                 "to data exfiltration, unauthorized transactions, or full account takeover.",
    "takeover": "An attacker can serve arbitrary content from a trusted subdomain, "
                "enabling phishing, session-cookie theft, CSP bypass, or OAuth token "
                "hijacking targeting users of this domain.",
    "nuclei": "Exploitation of this vulnerability may allow an attacker to compromise "
              "the confidentiality, integrity, or availability of the affected system.",
    "trufflehog": "Exposed credentials can be used immediately to access sensitive "
                  "data or infrastructure without any further exploitation steps.",
    "secretfinder": "Hardcoded credentials in client-side JavaScript are accessible "
                    "to any visitor and can be extracted without authentication.",
}


def draft(finding: Finding, program_url: str = "") -> str:
    """
    Generate a complete H1-ready report Markdown string from a Finding.

    The output can be pasted directly into HackerOne's report submission form
    or opened in an editor for final review before submission.
    """
    severity_label = _SEVERITY_LABEL.get(finding.severity, "Medium")
    cvss_range = _CVSS_BY_SEVERITY.get(finding.severity, "")
    cvss_str = f"{finding.cvss:.1f}" if finding.cvss else cvss_range
    cwe_str = f" ({finding.cwe})" if finding.cwe else ""

    impact = finding.impact or _IMPACT_BY_TOOL.get(finding.source_tool, "")

    lines: list[str] = [
        f"# {finding.title}",
        "",
        f"**Severity:** {severity_label}  ",
        f"**Asset:** `{finding.asset}`  ",
        f"**CVSS:** {cvss_str}{cwe_str}  ",
        f"**Discovered by:** `{finding.source_tool}`  ",
        f"**Confidence:** {finding.confidence * 100:.0f}%  ",
        "",
        "---",
        "",
        "## Summary",
        "",
        finding.description or f"A {severity_label.lower()} severity issue was identified on `{finding.asset}`.",
        "",
        "## Steps To Reproduce",
        "",
    ]

    if finding.poc:
        # Normalize PoC: ensure each step starts on its own line
        poc_lines = finding.poc.strip().splitlines()
        for i, step in enumerate(poc_lines, 1):
            step = step.strip().lstrip("0123456789.-) ")
            if step:
                lines.append(f"{i}. {step}")
    else:
        lines += [
            f"1. Navigate to `{finding.asset}`",
            "2. [Document exact reproduction steps here]",
            "3. Observe the vulnerability described above.",
        ]

    lines += [
        "",
        "## Supporting Material / Evidence",
        "",
        "```",
        (finding.evidence or "[Attach screenshot or HTTP request/response]")[:3000],
        "```",
        "",
        "## Impact",
        "",
        impact or f"This {severity_label.lower()} severity finding may allow an attacker to compromise the affected asset.",
    ]

    if finding.remediation:
        lines += [
            "",
            "## Remediation",
            "",
            finding.remediation,
        ]

    lines += [
        "",
        "---",
        "",
        f"*Report generated by recon-agent on "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*",
    ]

    if program_url:
        lines.append(f"*Program: {program_url}*")

    return "\n".join(lines)


def draft_to_file(finding: Finding, output_path: str, program_url: str = "") -> str:
    """Write draft to a file and return the path."""
    from pathlib import Path
    content = draft(finding, program_url)
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return str(path)
